name: Daily News Update

on:
  # 매일 오전 9시(KST)에 실행 (UTC 기준 00:00)
  schedule:
    - cron: '34 21 * * *'
  # 수동 실행을 위한 워크플로우 디스패치
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to fetch news and generate HTML
        # GitHub Secrets를 환경 변수로 스크립트에 전달
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          # 파일 변경이 있을 경우에만 커밋
          git diff --staged --quiet || git commit -m "Update daily news for $(date +'%Y-%m-%d')"
          git push
